
FROM node:alpine

WORKDIR /app

COPY ./package*.json ./

RUN npm install

RUN npm install -g live-server

COPY ./src ./src

EXPOSE 3000

CMD ["live-server", "src", "--port=3000", "--host=0.0.0.0", "--no-browser"]
