services:
  nginx:
    image: nginx:latest
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/src:/usr/share/nginx/html
      - ./backend/uploads:/var/www/html/uploads
      - ./frontend/public:/usr/share/nginx/html/images
      - ./certs:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443" 
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/uploads:/var/www/html/uploads
      - ./frontend/public:/stickers
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
  #    dockerfile: Dockerfile-dev 
  #  volumes:
  #    - ./frontend/src:/app/src
  #    - ./frontend/public:/app/public
  #  environment:
  #    - NODE_ENV=development
    expose:
      - "80"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - camagru_db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --skip-ssl

volumes:
  camagru_db_data: