services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/uploads:/var/www/html/uploads
      - ./frontend/public:/stickers
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    expose:
      - "8080"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - camagru_db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --skip-ssl

volumes:
  camagru_db_data: